pull_request_rules:
  - name: Automatic merge on approval
    conditions:
        - or:
          - author=StephanAkkerman
          - author=TimKoornstra
          - author~=^dependabot(|-preview)\[bot\]$
          - author=imgbot[bot]
    actions:
      merge:
        method: merge
